### ISSUE TITLE
Unable to run with sample inputs

### ISSUE THREAD

**Issue by dww100** [magnitov/protease_annotation_pipeline#1]
I am trying to test out your code and ran into the following error using the supplied sample input. I ran

```
python 02_find_pockets.py --input sample_data_pockets.csv --ref 3tjv --extra_ref 1iau,1ox1,1hne,1ab9 --radius 4.5 --cutoff 2
```

and got the following error:

```
Traceback (most recent call last):
  File "/mnt/store/projects/protease-project-support/protease_annotation_pipeline/02_find_pockets.py", line 308, in <module>
    reference_ligand_coordinates, reference_protein_coordinates = get_protein_and_ligand_coordinates(data, reference_structure)
  File "/mnt/store/projects/protease-project-support/protease_annotation_pipeline/02_find_pockets.py", line 40, in get_protein_and_ligand_coordinates
    protein_coords_sup = open('./pockets/protein_ligand_' + pdb_code + '.pdb', 'r').readlines()
FileNotFoundError: [Errno 2] No such file or directory: './pockets/protein_ligand_3tjv.pdb'
```

Could you give me any pointers please?

**Comment by magnitov** [comment]
Dear @dww100,

Indeed, I believe I forgot to add superimposed PDB files for the sample input. I added the folder **./pockets** with extracted protein+ligand chains, which should solve the problem.

Best,
Mikhail

**Comment by dww100** [comment]
Perfect - works for me now :)
